CREATE VIEW VIEW_USER_INFORMATION AS
SELECT USRS.USER_ID, USRS.FIRST_NAME, USRS.LAST_NAME, USRS.YEAR_OF_BIRTH, USRS.MONTH_OF_BIRTH, USRS.DAY_OF_BIRTH, USRS.GENDER,
        CURR_CITIES.CITY_NAME AS CURRENT_CITY, CURR_CITIES.STATE_NAME AS CURRENT_STATE, CURR_CITIES.COUNTRY_NAME AS CURRENT_COUNTRY,
        HT_CITIES.CITY_NAME AS HOMETOWN_CITY, HT_CITIES.STATE_NAME AS HOMETOWN_STATE, HT_CITIES.COUNTRY_NAME AS HOMETOWN_COUNTRY, 
        PROG.INSTITUTION AS INSTITUTION_NAME, EDU.PROGRAM_YEAR, PROG.CONCENTRATION AS PROGRAM_CONCENTRATION, PROG.DEGREE AS PROGRAM_DEGREE
FROM USERS USRS
LEFT JOIN USER_CURRENT_CITIES UCC
    INNER JOIN CITIES CURR_CITIES
    ON (UCC.CURRENT_CITY_ID = CURR_CITIES.CITY_ID)
ON (USRS.USER_ID = UCC.USER_ID)
LEFT JOIN USER_HOMETOWN_CITIES UHC
    INNER JOIN CITIES HT_CITIES
    ON (UHC.HOMETOWN_CITY_ID = HT_CITIES.CITY_ID)
ON (USRS.USER_ID = UHC.USER_ID)
LEFT JOIN EDUCATION EDU
    INNER JOIN PROGRAMS PROG
    ON (EDU.PROGRAM_ID = PROG.PROGRAM_ID)
ON (USRS.USER_ID = EDU.USER_ID);

CREATE VIEW VIEW_ARE_FRIENDS AS
SELECT * FROM FRIENDS;

CREATE VIEW VIEW_PHOTO_INFORMATION AS
SELECT A.ALBUM_ID, ALBUM_OWNER_ID AS OWNER_ID, ALBUM_NAME, ALBUM_CREATED_TIME,
        ALBUM_MODIFIED_TIME, ALBUM_LINK, ALBUM_VISIBILITY, PHOTO_ID,
        PHOTO_CAPTION, PHOTO_CREATED_TIME, PHOTO_MODIFIED_TIME, PHOTO_LINK
FROM ALBUMS A
LEFT JOIN PHOTOS B
ON (A.ALBUM_ID = B.ALBUM_ID);

CREATE VIEW VIEW_EVENT_INFORMATION AS
SELECT EVENT_ID, EVENT_CREATOR_ID, EVENT_NAME, EVENT_TAGLINE,
        EVENT_DESCRIPTION, EVENT_HOST, EVENT_TYPE, EVENT_SUBTYPE,
        EVENT_ADDRESS, B.CITY_NAME AS EVENT_CITY,
        B.STATE_NAME AS EVENT_STATE, B.COUNTRY_NAME AS EVENT_COUNTRY,
        EVENT_START_TIME, EVENT_END_TIME
FROM USER_EVENTS A
LEFT JOIN CITIES B
ON (A.EVENT_CITY_ID = B.CITY_ID);

CREATE VIEW VIEW_TAG_INFORMATION AS
SELECT TAG_PHOTO_ID AS PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME,
        TAG_X AS TAG_X_COORDINATE, TAG_Y AS TAG_Y_COORDINATE
FROM TAGS;