CREATE TABLE USERS (
    USER_ID INTEGER NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR2(100) NOT NULL,
    LAST_NAME VARCHAR2(100) NOT NULL,
    YEAR_OF_BIRTH INTEGER,
    MONTH_OF_BIRTH INTEGER,
    DAY_OF_BIRTH INTEGER,
    GENDER VARCHAR2(100)
);

CREATE TABLE FRIENDS (
    USER1_ID INTEGER NOT NULL,
    USER2_ID INTEGER NOT NULL,
    PRIMARY KEY (USER1_ID, USER2_ID),
    CONSTRAINT UNIQUE_PAIR UNIQUE (USER2_ID, USER1_ID),
    CHECK (USER1_ID != USER2_ID),
    FOREIGN KEY (USER1_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER2_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE
);

CREATE TABLE CITIES (
    CITY_ID INTEGER NOT NULL PRIMARY KEY,
    CITY_NAME VARCHAR2(100) NOT NULL,
    STATE_NAME VARCHAR2(100) NOT NULL,
    COUNTRY_NAME VARCHAR2(100) NOT NULL,
    CONSTRAINT UNIQUE_TRIO_C UNIQUE (CITY_NAME, STATE_NAME, COUNTRY_NAME)
);

CREATE TABLE USER_CURRENT_CITIES (
    USER_ID INTEGER NOT NULL PRIMARY KEY,
    CURRENT_CITY_ID INTEGER NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (CURRENT_CITY_ID) REFERENCES CITIES (CITY_ID) ON DELETE CASCADE
);

CREATE TABLE USER_HOMETOWN_CITIES (
    USER_ID INTEGER NOT NULL PRIMARY KEY,
    HOMETOWN_CITY_ID INTEGER NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (HOMETOWN_CITY_ID) REFERENCES CITIES (CITY_ID) ON DELETE CASCADE
);

CREATE TABLE MESSAGES (
    MESSAGE_ID INTEGER NOT NULL PRIMARY KEY,
    SENDER_ID INTEGER NOT NULL,
    RECEIVER_ID INTEGER NOT NULL,
    MESSAGE_CONTENT VARCHAR2(2000) NOT NULL,
    SENT_TIME TIMESTAMP NOT NULL,
    FOREIGN KEY (SENDER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (RECEIVER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE
);

CREATE TABLE PROGRAMS (
    PROGRAM_ID INTEGER NOT NULL PRIMARY KEY,
    INSTITUTION VARCHAR2(100) NOT NULL,
    CONCENTRATION VARCHAR2(100) NOT NULL,
    DEGREE VARCHAR2(100) NOT NULL,
    CONSTRAINT UNIQUE_TRIO_P UNIQUE (INSTITUTION, CONCENTRATION, DEGREE)
);

CREATE TABLE EDUCATION (
    USER_ID INTEGER NOT NULL,
    PROGRAM_ID INTEGER NOT NULL,
    PROGRAM_YEAR INTEGER NOT NULL,
    PRIMARY KEY (USER_ID, PROGRAM_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (PROGRAM_ID) REFERENCES PROGRAMS (PROGRAM_ID) ON DELETE CASCADE
);

CREATE TABLE USER_EVENTS (
    EVENT_ID INTEGER NOT NULL UNIQUE,
    EVENT_CREATOR_ID INTEGER NOT NULL,
    EVENT_NAME VARCHAR2(100) NOT NULL,
    EVENT_TAGLINE VARCHAR2(100),
    EVENT_DESCRIPTION VARCHAR2(100),
    EVENT_HOST VARCHAR2(100),
    EVENT_TYPE VARCHAR2(100),
    EVENT_SUBTYPE VARCHAR2(100),
    EVENT_ADDRESS VARCHAR2(2000),
    EVENT_CITY INTEGER NOT NULL,
    EVENT_START_TIME TIMESTAMP,
    EVENT_END_TIME TIMESTAMP,
    PRIMARY KEY (EVENT_ID, EVENT_CREATOR_ID, EVENT_CITY),
    FOREIGN KEY (EVENT_CREATOR_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (EVENT_CITY) REFERENCES CITIES (CITY_ID) ON DELETE CASCADE
);

CREATE TABLE PARTICIPANTS (
    EVENT_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    CONFIRMATION VARCHAR2(100) NOT NULL,
    PRIMARY KEY (EVENT_ID, USER_ID),
    CHECK (CONFIRMATION IN ('ATTENDING', 'UNSURE', 'DECLINES', 'NOT_REPLIED')),
    FOREIGN KEY (EVENT_ID) REFERENCES USER_EVENTS (EVENT_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE
);


CREATE TABLE ALBUMS (
    ALBUM_ID INTEGER NOT NULL PRIMARY KEY,
    ALBUM_OWNER INTEGER NOT NULL,
    ALBUM_NAME VARCHAR2(100) NOT NULL,
    ALBUM_CREATED_TIME TIMESTAMP NOT NULL,
    ALBUM_MODIFIED_TIME TIMESTAMP,
    ALBUM_LINK VARCHAR2(100) NOT NULL,
    ALBUM_VISIBILITY VARCHAR2(100) NOT NULL,
    COVER_PHOTO_ID INTEGER NOT NULL,
    CHECK (ALBUM_VISIBILITY IN ('EVERYONE', 'FRIENDS', 'FRIENDS_OF_FRIENDS', 'MYSELF')),
    FOREIGN KEY (ALBUM_OWNER) REFERENCES USERS (USER_ID) ON DELETE CASCADE
);

CREATE TABLE PHOTOS (
    PHOTO_ID INTEGER NOT NULL PRIMARY KEY,
    ALBUM_ID INTEGER NOT NULL,
    PHOTO_CAPTION VARCHAR2(2000),
    PHOTO_CREATED_TIME TIMESTAMP NOT NULL,
    PHOTO_MODIFIED_TIME TIMESTAMP,
    PHOTO_LINK VARCHAR2(2000) NOT NULL
);

CREATE TABLE TAGS (
    PHOTO_ID INTEGER NOT NULL,
    TAG_SUBJECT_ID INTEGER NOT NULL,
    TAG_CREATED_TIME TIMESTAMP NOT NULL,
    TAG_X_COORDINATE INTEGER NOT NULL,
    TAG_Y_COORDINATE INTEGER NOT NULL,
    PRIMARY KEY (PHOTO_ID, TAG_SUBJECT_ID),
    FOREIGN KEY (TAG_SUBJECT_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (PHOTO_ID) REFERENCES PHOTOS (PHOTO_ID) ON DELETE CASCADE
);

-- NEEDED FOR CIRCULAR DEPENDENCY BETWEEN ALBUMS AND PHOTOS
ALTER TABLE ALBUMS
ADD CONSTRAINT PHOTO_EXISTS FOREIGN KEY (COVER_PHOTO_ID) REFERENCES PHOTOS (PHOTO_ID)
ON DELETE CASCADE
INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE PHOTOS
ADD CONSTRAINT ALBUM_EXISTS FOREIGN KEY (ALBUM_ID) REFERENCES ALBUMS (ALBUM_ID)
ON DELETE CASCADE
INITIALLY DEFERRED DEFERRABLE;

CREATE SEQUENCE CITY_ID_SEQUENCE
    START WITH 1
    INCREMENT BY 1;

CREATE TRIGGER ADD_CITY
    BEFORE INSERT ON CITIES 
    FOR EACH ROW
        BEGIN
            SELECT CITY_ID_SEQUENCE.NEXTVAL INTO :NEW.CITY_ID FROM DUAL; 
        END;
/

CREATE SEQUENCE PROGRAM_ID_SEQUENCE 
    START WITH 1
    INCREMENT BY 1;

CREATE TRIGGER ADD_PROGRAM
    BEFORE INSERT ON PROGRAMS 
        FOR EACH ROW
            BEGIN
                SELECT PROGRAM_ID_SEQUENCE.NEXTVAL INTO :NEW.PROGRAM_ID FROM DUAL; 
            END;
/

CREATE TRIGGER ORDER_FRIEND_PAIRS
    BEFORE INSERT ON FRIENDS
    FOR EACH ROW
        DECLARE temp INTEGER;
        BEGIN
            IF :NEW.USER1_ID > :NEW.USER2_ID THEN
                temp := :NEW.USER2_ID;
                :NEW.USER2_ID := :NEW.USER1_ID;
                :NEW.USER1_ID := temp;
            END IF;
        END;
/
