CREATE VIEW VIEW_USER_INFORMATION AS
SELECT USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER
FROM USERS;

CREATE VIEW VIEW_ARE_FRIENDS

CREATE VIEW VIEW_PHOTO_INFORMATION

CREATE VIEW VIEW_EVENT_INFORMATION

CREATE VIEW VIEW_TAG_INFORMATION