CREATE SEQUENCE CITY_ID_SEQUENCE 
    START WITH 1
    INCREMENT BY 1;
CREATE TRIGGER Add_City 
    BEFORE INSERT ON CITIES 
    FOR EACH ROW
        BEGIN
            SELECT CITY_ID_SEQUENCE.NEXTVAL INTO :NEW.CITY_ID FROM DUAL; 
        END;
/

CREATE SEQUENCE PROGRAM_ID_SEQUENCE 
    START WITH 1
    INCREMENT BY 1;
CREATE TRIGGER Add_Program 
    BEFORE INSERT ON PROGRAMS 
        FOR EACH ROW
            BEGIN
                SELECT PROGRAM_ID_SEQUENCE.NEXTVAL INTO :NEW.PROGRAM_ID FROM DUAL; 
            END;
/

CREATE TRIGGER Order_Friend_Pairs
    BEFORE INSERT ON FRIENDS
    FOR EACH ROW
        DECLARE temp INTEGER;
        BEGIN
            IF :NEW.USER1_ID > :NEW.USER2_ID THEN
                temp := :NEW.USER2_ID;
                :NEW.USER2_ID := :NEW.USER1_ID;
                :NEW.USER1_ID := temp;
            END IF;
        END;
/

SET AUTOCOMMIT OFF;

INSERT INTO USERS (USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH)
SELECT USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH FROM project1.PUBLIC_USER_INFORMATION;

INSERT INTO FRIENDS
SELECT * FROM project1.PUBLIC_ARE_FRIENDS;

INSERT INTO PHOTOS
SELECT * FROM project1.PUBLIC_PHOTO_INFORMATION;

INSERT INTO TAGS
SELECT * FROM project1.PUBLIC_TAG_INFORMATION;

INSERT INTO USER_EVENTS
SELECT * FROM project1.PUBLIC_EVENT_INFORMATION;

COMMIT;
SET AUTOCOMMIT ON;