CREATE SEQUENCE city_id_sequence START WITH 1
INCREMENT BY 1;
CREATE TRIGGER add_city BEFORE INSERT ON Cities FOR EACH ROW
BEGIN
SELECT city_id_sequence.NEXTVAL INTO :NEW.city_id FROM DUAL; END;
/

CREATE SEQUENCE program_id_sequence START WITH 1
INCREMENT BY 1;
CREATE TRIGGER add_program BEFORE INSERT ON Programs FOR EACH ROW
BEGIN
SELECT program_id_sequence.NEXTVAL INTO :NEW.program_id FROM DUAL; END;
/

CREATE TRIGGER Order_Friend_Pairs BEFORE INSERT ON FRIENDS
/
FOR EACH ROW
DECLARE temp INTEGER;
BEGIN
IF :NEW.USER1_ID > :NEW.USER2_ID THEN
temp := :NEW.USER2_ID; :NEW.USER2_ID := :NEW.USER1_ID; :NEW.USER1_ID := temp;
END IF ; END;